name: ArgoCD App Sync
description: Sync an app on ArgoCD
inputs:
  server:
    description: ArgoCD Server Endpoint
    required: true
  cli_server:
    description: ArgoCD CLI Download Server Endpoint, defaults to `server`
  auth_token:
    description: ArgoCD Auth Token
    required: true
  app:
    description: ArgoCD App Name
    required: true
outputs:
  env_url:
    description: App Environment URL
runs:
  using: docker
  image: Dockerfile
  env:
    ARGOCD_SERVER: ${{ inputs.server }}
    ARGOCD_CLI_SERVER: ${{ inputs.cli_server || inputs.server }}
    ARGOCD_AUTH_TOKEN: ${{ inputs.auth_token }}
  args:
    - ${{ inputs.app }}
